# Site settings
author: Hector Jimenez
title: One Dream at a Time
header-img: img/home-bg.png
email: hjmontemayor@gmail.com
copyright_name: Hector Jimenez
description: > # this means to ignore newlines until "baseurl:"
  Sharing experiences of the coding trip
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Hectorjmz

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
